export const FETCH_STUDENTS_DATA_REQUEST = 'FETCH_STUDENTS_DATA_REQUEST';
export const FETCH_STUDENTS_DATA_SUCCESS = 'FETCH_STUDENTS_DATA_SUCCESS';
export const FETCH_STUDENTS_DATA_FAILURE = 'FETCH_STUDENTS_DATA_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_SINGLE_STUDENT_REQUEST = 'GET_SINGLE_STUDENT_REQUEST';
export const GET_SINGLE_STUDENT_SUCCESS = 'GET_SINGLE_STUDENT_SUCCESS';
export const GET_SINGLE_STUDENT_FAILURE = 'GET_SINGLE_STUDENT_FAILURE';

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const CHECK_USER_AUTH_REQUEST = "CHECK_USER_AUTH_REQUEST";
export const CHECK_USER_AUTH_SUCCESS = "CHECK_USER_AUTH_SUCCESS";
export const CHECK_USER_AUTH_FAILURE = "CHECK_USER_AUTH_FAILURE";

export const FILTER_DATA_BY_YEAR_REQUEST = 'FILTER_DATA_BY_YEAR_REQUEST';
export const FILTER_DATA_BY_YEAR_SUCCESS = 'FILTER_DATA_BY_YEAR_SUCCESS';
export const FILTER_DATA_BY_YEAR_FAILURE = 'FILTER_DATA_BY_YEAR_FAILURE';

export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST';
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
export const SEARCH_DATA_FAILURE = 'SEARCH_DATA_FAILURE';

export const SEND_NOTIFICATION_FAILURE = 'SEND_NOTIFICATION_FAILURE';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';