export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const CHECK_USER_AUTH_REQUEST = "CHECK_USER_AUTH_REQUEST";
export const CHECK_USER_AUTH_SUCCESS = "CHECK_USER_AUTH_SUCCESS";
export const CHECK_USER_AUTH_FAILURE = "CHECK_USER_AUTH_FAILURE";

export const UPLOAD_DETAIL_REQUEST = "UPLOAD_DETAIL_REQUEST";
export const UPLOAD_DETAIL_SUCCESS = "UPLOAD_DETAIL_SUCCESS";
export const UPLOAD_DETAIL_FAILURE = "UPLOAD_DETAIL_FAILURE";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";

export const UPDATE_VEHICLE_DETAILS_REQUEST = "UPDATE_VEHICLE_DETAILS_REQUEST";
export const UPDATE_VEHICLE_DETAILS_SUCCESS = "UPDATE_VEHICLE_DETAILS_SUCCESS";
export const UPDATE_VEHICLE_DETAILS_FAILURE = "UPDATE_VEHICLE_DETAILS_FAILURE";

export const UPLOAD_VEHICLE_DETAIL_REQUEST = "UPLOAD_VEHICLE_DETAIL_REQUEST";
export const UPLOAD_VEHICLE_DETAIL_SUCCESS = "UPLOAD_VEHICLE_DETAIL_SUCCESS";
export const UPLOAD_VEHICLE_DETAIL_FAILURE = "UPLOAD_VEHICLE_DETAIL_FAILURE";

export const UPLOAD_PROFILE_IMAGE_REQUEST = "UPLOAD_PROFILE_IMAGE_REQUEST";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_FAILURE = "UPLOAD_PROFILE_IMAGE_FAILURE";